services:
  - type: web
    name: portfolio-backend
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio_user
    plan: free